### PR TITLE
added unit tests to validate the calculator service

### PR DESCRIPTION
**Pull request by bryanallott**
thank you for the effort in submitting the assignment. i've added unit tests here to validate the calculation function without needing to host the API.

### CODE REVIEW

**Comment by RetroRootz** [comment]
Hi there

Are you from the Convergancy Hub?
Thanks for the unit tests.

**Comment by bryanallott** [comment]
Hellooo, yes. My name is Bryan. I got your submission via Datafin from our HR department. Nice submission. Straight forward and to the point. It'll work nicely as a point of reference for a discussion I think.

**Comment by RetroRootz** [comment]
Okay great! Hi Brian, thanks..I was wondering who was talking to me lol coz
I never gave access, but I know it's public.
See you then! :)

**Comment by bryanallott** [comment]
lol. looking forward to catching up. I'm sure our team will be in contact with your team soon. 
some of the things I as thinking about as I was reading through your code: 

- choice of react + API as toolchain and design choice: pros and cons, likes and dislikes
- favourite IDEs
- how else could you design the solution?
- why the use of the ICalculatorService interface?
- how would you go about securing the API for subsequent logins/calculations (like a history of saved calculations per registered user)
- maths. we use a lot of maths in some of our products. how comfortable are you beyond interest calculation basics?
- linq2db vs entityframework: was this an intentional decision?

we can chat through those and others when we meet. cheers!

**Pull request merged**
